[package]
name = "generator"
version = "0.1.0"
edition = "2025"

[dependencies]
tensorlib = { path = "../tensorlib" }
state_dict = { path = "../state_dict" }
nn = { path = "../nn" }
tiktoken-rs = "0.5.9"
anyhow = "1.0.75"
base64 = "0.22.1"
rustc-hash = "1.1.0"
serde = "1.0.210"
log = "0.4.22"
getrandom = { version = "0.2.12", features = ["js"] }
rand = { version = "0.8.5", features = ["small_rng"] }
web-time = "1.1.0"
wasm-bindgen-test = "0.3"
